version: "3.8"
services:
  dependency_resolving:
    build: .
    command: --filter *DependencyResolvingBenchmarks*
    privileged: true
  clean_cache:
    build: .
    command: --filter *CleanCacheBenchmarks*
    privileged: true
  microsoft_cache:
    build: .
    command: --filter *MicrosoftCacheBenchmarks*
    privileged: true
  clean_cachingloader:
    build: .
    command: --filter *CleanCachingLoaderBenchmarks*
    privileged: true